apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base
  - namespace.yaml
  - servicemonitor.yaml

namespace: prod


patches:
  - path: patch-deployment.yaml
  - path: patch-hpa.yaml
