apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: obsapp
  labels:
    app: obsapp
spec:
  selector:
    matchLabels:
      app: obsapp
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
